### ISSUE TITLE
Cuda out of memory.

### ISSUE THREAD

**Issue by TomassMa** [hkchengrex/STCN#120]
Hey, i have similiar issue to #23 , I'm trying to use slightly altered (only a compatibility changes) eval_generic to segment some videos from  [this dataset](https://web.engr.oregonstate.edu/~lif/SegTrack2/dataset.html). The problem is I keep running out of memory, im using google colab workspace and getting RuntimeError: CUDA out of memory. Tried to allocate 2.97 GiB (GPU 0; 14.76 GiB total capacity; 9.57 GiB already allocated; 319.75 MiB free; 13.13 GiB reserved in total by PyTorch).

It happens at line:  processor.interact(with_bg_msk, frame_idx, frames_with_gt[i+1]+1, obj_idx)

I've already increased the mem-every argument, but it didn't really help, can you by any chance think of something that i can change ?

**Comment by TomassMa** [comment]
Nevermind, i found the cause of my issue, it was similar as in #3. 

Anyway thank you for your work :)

**Comment by dongho-Han** [comment]
Hello, @TomassMa & @hkchengrex !
I'm trying to run STCN with custom dataset(HO3D), but i fails with with the same error with you..
As I printed my `self.k`, it's value is 2. So I think my error is slightly different from #3 .
Also, as my error comes from 'processor.interact(with_bg_msk, frame_idx, frames_with_gt[i+1]+1, obj_idx)' this line with 'RuntimeError: CUDA out of memory.' message, I think it is related to the GPU memory problem(although my GPU has almost 24GB).
So, could you share how you solve this problem?

Thanks:)
