### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched

### ISSUE THREAD

**Issue by JerryX1110** [hkchengrex/STCN#7]
raceback (most recent call last):
  File "eval_youtube.py", line 133, in <module>
    processor.interact(with_bg_msk, frame_idx, rgb.shape[1], obj_idx)
  File "/datasets/MODELS/STCN-ALL/STCN/inference_core_yv.py", line 123, in interact
    self.do_pass(key_k, key_v, frame_idx, end_idx)
  File "/datasets/MODELS/STCN-ALL/STCN/inference_core_yv.py", line 84, in do_pass
    for oi in self.enabled_obj], 0)
  File "/datasets/MODELS/STCN-ALL/STCN/inference_core_yv.py", line 84, in <listcomp>
    for oi in self.enabled_obj], 0)
  File "/datasets/MODELS/STCN-ALL/STCN/model/eval_network.py", line 61, in segment_with_query
    readout_mem = mem_bank.match_memory(qk16)
  File "/datasets/MODELS/STCN-ALL/STCN/inference_memory_bank.py", line 60, in match_memory
    readout_mem = self._readout(affinity.expand(k,-1,-1), mv)
  File "/datasets/MODELS/STCN-ALL/STCN/inference_memory_bank.py", line 42, in _readout
    return torch.bmm(mv, affinity)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

**Comment by hkchengrex** [comment]
Never saw this error before. More details?

**Comment by JerryX1110** [comment]
I trained the model successfully. However, it failed when inferencing. It's really strange.

**Comment by hkchengrex** [comment]
... You can infer with the downloaded model but not with your trained one?
Are the file sizes the same?

**Comment by JerryX1110** [comment]
It seems there is a slight difference between the trained one (218027308) and the downloaded one (218027692).

**Comment by JerryX1110** [comment]
It also failed for the downloaded one and raised the same error.

**Comment by hkchengrex** [comment]
Probably has something to do with `amp`. Cannot test it right now but you can try adding/removing it in inference.

**Comment by JerryX1110** [comment]
What does 'amp' mean?

**Comment by hkchengrex** [comment]
It means automatic mixed precision. If you don't know what it is you are probably not using it.
I just tried it on my computer and it works with and without AMP, so the problem might be on your side.
See https://github.com/pytorch/pytorch/issues/29795

**Comment by JerryX1110** [comment]
Thank you I'll try :)

**Comment by JerryX1110** [comment]
I've tried the method above as well as other solutions. However, I still couldn't solve the problem. @hkchengrex  Could you provide a  docker image for this project?

**Comment by hkchengrex** [comment]
I have no plan to use docker. Maybe you can try pinpointing the line that causes the error -- assuming you can run other PyTorch models just fine.

**Comment by JerryX1110** [comment]
Okay, I'll try my best to solve the bug. If I manage to solve it, maybe I can provide a docker image for this repo.

**Comment by JerryX1110** [comment]
Finally, I solved this problem by replacing a GPU server (as I run the code on the cluster). I think this problem is probably caused by certain NVIDIA Driver or CUDA versions.  Anyway, thanks for your helping.

**Comment by JerryX1110** [comment]
Actually, I find that this error occurs without AMP but disappeared with AMP.  Just weird.

**Comment by hkchengrex** [comment]
For both servers?
As I said it didn't occur for me with/without AMP (CUDA 10/CUDA 11) so yeah it is weird.
If you can reproduce it with a minimum working example, you can raise an issue in PyTorch's repo.

**Comment by JerryX1110** [comment]
I think it's maybe a bug of pytorch. My CUDA is 11.0 and the bug only occurred without AMP.

**Comment by JerryX1110** [comment]
By the way, this code really works. I succeeded in reproducing the number in the paper in 'w/o BL30K' setting. Great and neat work!

**Comment by hkchengrex** [comment]
Feel free to comment/reopen if there is a solution or if the problem is found.

**Comment by blessingforever** [comment]
> By the way, this code really works. I succeeded in reproducing the number in the paper in 'w/o BL30K' setting. Great and neat work!

Hi, I have also tried the 'w/o BL30K' setting. The numbers for DAVIS 2016 and YouTube-VOS seem right (91.5%, 83.0%), but the result for DAVIS 2017 is 84.2%, which is 1.2% lower than the official number. Can you reproduce the number in all three benchmarks?

**Comment by caldwecg** [comment]
Any updates on how to solve this? Getting the same error with PyTorch version: 1.12.1+cu116 on Turing 32GiB GPU:

RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling cublasGemmStridedBatchedExFix(...)

**Comment by CarettaCaretta11** [comment]
> Any updates on how to solve this? Getting the same error with PyTorch version: 1.12.1+cu116 on Turing 32GiB GPU:
> 
> RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling cublasGemmStridedBatchedExFix(...)

Did you manage to solve it?
